DEFAULT_PORT = 7777
STOP_AND_WAIT_PROTOCOL_TYPE = "saw"
GO_BACK_N_PROTOCOL_TYPE = "gbn"
IPV4_LOCALHOST = "127.0.0.1"
USE_ANY_AVAILABLE_PORT = 0

ZERO_BYTES = bytes([])
FULL_BUFFER_SIZE = 65535
COMMS_BUFFER_SIZE = 2048

DOWNLOAD_OPERATION = 0
UPLOAD_OPERATION = 1

ERROR_EXIT_CODE = 1

STRING_ENCODING_FORMAT = "utf-8"
FOPEN_READ_MODE = "r"
FOPEN_WRITE_TRUNCATE_MODE = "w+"
FOPEN_WRITE_APPEND_MODE = "a"
FOPEN_BINARY_MODE = "b"

FILE_CHUNK_SIZE = 61440
