DEFAULT_PORT = 7777
STOP_AND_WAIT_PROTOCOL_TYPE = "saw"
GO_BACK_N_PROTOCOL_TYPE = "gbn"
IPV4_LOCALHOST = "127.0.0.1"

USE_ANY_AVAILABLE_PORT = 0
USE_CURRENT_HOST = ""

SOCKET_CONNECTION_LOST_TIMEOUT = 30.0
SOCKET_RETRANSMISSION_TIMEOUT = 0.015
MAX_RETRANSMISSION_ATTEMPTS = 150

WINDOW_SIZE = 10
SOCKET_RETRANSMIT_WINDOW_TIMEOUT = 0.1

ZERO_BYTES = bytes([])
FULL_BUFFER_SIZE = 3072  # 3 kB
COMMS_BUFFER_SIZE = 2048  # 2 kB

DOWNLOAD_OPERATION = 1
UPLOAD_OPERATION = 2

OPERATION_STRING_FROM_CODE = {
    DOWNLOAD_OPERATION: "DOWNLOAD",
    UPLOAD_OPERATION: "UPLOAD",
}

ERROR_EXIT_CODE = 1

STRING_ENCODING_FORMAT = "utf-8"
INT_DESERIALIZATION_BYTEORDER = "big"

FOPEN_READ_MODE = "r"
FOPEN_WRITE_TRUNCATE_MODE = "w+"
FOPEN_BINARY_MODE = "b"

HISTORICAL_MTU = 1500
MAX_IP_HEADER_SIZE = 60
UDP_HEADER_SIZE = 8
SAW_PROTOCOL_HEADER_SIZE = 6
GBN_PROTOCOL_HEADER_SIZE = 16

FILE_CHUNK_SIZE_SAW = (
    HISTORICAL_MTU - MAX_IP_HEADER_SIZE - UDP_HEADER_SIZE - SAW_PROTOCOL_HEADER_SIZE
)

FILE_CHUNK_SIZE_GBN = (
    HISTORICAL_MTU - MAX_IP_HEADER_SIZE - UDP_HEADER_SIZE - GBN_PROTOCOL_HEADER_SIZE
)
