name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  check-pep8:
    runs-on: ubuntu-latest
    steps:
      - name: ruff-action
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
