name: Integration tests

on:
  push:
    branches:
      - main
      - dev
      - gbn
  pull_request:
    branches:
      - main
      - dev
      - gbn

jobs:
  pytest:
    runs-on: ubuntu-24.04

    # Important: need privileged mode for Mininet!
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mininet
          sudo apt install -y openvswitch-testcontroller
          sudo apt install -y iproute2 iputils-ping net-tools
          sudo mn --clean

      - name: Set up virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          chmod +x ./test.sh
          sudo ./test.sh
